import type { Course, BlogPost, PricingPlan, Testimonial, FAQItem, Certification, ServiceRequest, Notification } from "@/types";

export const NAV_ITEMS = [
  { label: "Home", href: "/" },
  { label: "Features", href: "/features" },
  { label: "Courses", href: "/features#courses" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const COURSES: Course[] = [
  {
    id: "1",
    title: "Complete MS Office Mastery",
    description: "Master Word, Excel, PowerPoint, and Outlook for professional productivity.",
    instructor: "Rahul Sharma",
    duration: "24 hours",
    level: "beginner",
    category: "Office Productivity",
    price: 1999,
    rating: 4.8,
    students: 12450,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=250&fit=crop",
    tags: ["MS Office", "Excel", "Word", "PowerPoint"],
  },
  {
    id: "2",
    title: "Full-Stack Web Development",
    description: "Build modern web applications with HTML, CSS, JavaScript, React, and Node.js.",
    instructor: "Priya Patel",
    duration: "80 hours",
    level: "intermediate",
    category: "Web Development",
    price: 4999,
    rating: 4.9,
    students: 8320,
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=250&fit=crop",
    tags: ["HTML", "CSS", "JavaScript", "React"],
  },
  {
    id: "3",
    title: "Python Programming Fundamentals",
    description: "Learn Python from scratch with hands-on projects and real-world applications.",
    instructor: "Amit Kumar",
    duration: "40 hours",
    level: "beginner",
    category: "Programming",
    price: 2999,
    rating: 4.7,
    students: 15200,
    image: "https://images.unsplash.com/photo-1526379879527-8559ecfcaec0?w=400&h=250&fit=crop",
    tags: ["Python", "Programming", "Data Science"],
  },
  {
    id: "4",
    title: "Tally Prime & Accounting",
    description: "Complete Tally Prime training with GST, payroll, and inventory management.",
    instructor: "Sunita Verma",
    duration: "32 hours",
    level: "beginner",
    category: "Accounting",
    price: 2499,
    rating: 4.6,
    students: 9870,
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=250&fit=crop",
    tags: ["Tally", "Accounting", "GST", "Finance"],
  },
  {
    id: "5",
    title: "Graphic Design with Adobe Suite",
    description: "Professional graphic design using Photoshop, Illustrator, and InDesign.",
    instructor: "Neha Singh",
    duration: "60 hours",
    level: "intermediate",
    category: "Design",
    price: 3999,
    rating: 4.8,
    students: 6540,
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=250&fit=crop",
    tags: ["Photoshop", "Illustrator", "Design"],
  },
  {
    id: "6",
    title: "Digital Marketing Complete",
    description: "SEO, Social Media, Google Ads, Email Marketing, and Analytics mastery.",
    instructor: "Vikram Joshi",
    duration: "48 hours",
    level: "intermediate",
    category: "Digital Marketing",
    price: 3499,
    rating: 4.7,
    students: 11200,
    image: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=400&h=250&fit=crop",
    tags: ["SEO", "Social Media", "Google Ads"],
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: 499,
    yearlyPrice: 399,
    description: "Perfect for individuals starting their IT learning journey.",
    features: [
      "Access to 20+ basic courses",
      "2 certification attempts per month",
      "Community forum access",
      "Mobile app access",
      "Basic progress tracking",
      "Email support",
    ],
    highlighted: false,
    cta: "Start Free Trial",
  },
  {
    id: "professional",
    name: "Professional",
    price: 1299,
    yearlyPrice: 999,
    description: "Ideal for professionals seeking career advancement and certifications.",
    features: [
      "Access to 100+ courses",
      "Unlimited certification attempts",
      "AI learning assistant",
      "Resume builder & job portal",
      "Live doubt sessions",
      "Priority email & chat support",
      "Digital certificate issuance",
      "Career guidance sessions",
    ],
    highlighted: true,
    cta: "Get Started",
    badge: "Most Popular",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 3999,
    yearlyPrice: 2999,
    description: "Complete solution for training institutes and businesses.",
    features: [
      "Unlimited courses & certifications",
      "Institute management system",
      "Batch & student management",
      "Custom branding",
      "Advanced analytics dashboard",
      "Hardware & repair services",
      "Dedicated account manager",
      "24/7 phone support",
      "API access",
      "White-label options",
    ],
    highlighted: false,
    cta: "Contact Sales",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Anjali Mehta",
    role: "Software Developer",
    company: "TechCorp India",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face",
    content: "CompuPoint transformed my career. The structured learning path and industry-recognized certifications helped me land my dream job at a top tech firm within 6 months.",
    rating: 5,
    course: "Full-Stack Web Development",
  },
  {
    id: "2",
    name: "Rajesh Gupta",
    role: "IT Manager",
    company: "GlobalBiz Solutions",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    content: "The enterprise plan for our training institute has been a game-changer. Managing 500+ students, batch scheduling, and automated certifications is now effortless.",
    rating: 5,
    course: "Enterprise Training Plan",
  },
  {
    id: "3",
    name: "Priya Krishnan",
    role: "Freelance Designer",
    company: "Creative Studio",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face",
    content: "The Graphic Design course with Adobe Suite is exceptional. The projects are real-world focused and the instructor feedback is incredibly detailed and actionable.",
    rating: 5,
    course: "Graphic Design with Adobe Suite",
  },
  {
    id: "4",
    name: "Suresh Nair",
    role: "Accountant",
    company: "FinancePro",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
    content: "Tally Prime certification from CompuPoint is widely recognized by employers. Got placed within 2 weeks of completing the course. Highly recommended for accounting students.",
    rating: 5,
    course: "Tally Prime & Accounting",
  },
  {
    id: "5",
    name: "Meera Pillai",
    role: "Digital Marketing Lead",
    company: "StartupHub",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&crop=face",
    content: "The AI learning assistant is brilliant. It personalizes my study schedule, answers technical questions instantly, and tracks my weak areas to improve my exam scores.",
    rating: 5,
    course: "Digital Marketing Complete",
  },
  {
    id: "6",
    name: "Amit Jain",
    role: "Computer Hardware Technician",
    company: "TechFix Services",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
    content: "The hardware repair service booking system is smooth. I get clear job assignments, customer details, and can update status in real-time. Business efficiency improved 3x.",
    rating: 5,
    course: "Hardware Support Services",
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: "1",
    question: "What types of courses does CompuPoint offer?",
    answer: "CompuPoint offers a comprehensive range of IT courses including Basic Computer Training, MS Office, Tally & Accounting, Programming (Python, Java, C++), Web Development, Graphic Design, Digital Marketing, Cybersecurity, Data Science, and more. All courses are designed by industry experts.",
    category: "Courses",
  },
  {
    id: "2",
    question: "Are CompuPoint certifications recognized by employers?",
    answer: "Yes, CompuPoint certifications are industry-recognized and accepted by thousands of employers across India and internationally. Our certification programs follow industry standards and are regularly updated to match market requirements.",
    category: "Certification",
  },
  {
    id: "3",
    question: "How does the AI Learning Assistant work?",
    answer: "Our AI Learning Assistant analyzes your learning patterns, identifies knowledge gaps, personalizes your study schedule, answers technical questions 24/7, provides troubleshooting guidance, and offers career recommendations based on your skill profile and market trends.",
    category: "AI Features",
  },
  {
    id: "4",
    question: "Can I access courses on mobile devices?",
    answer: "Absolutely! CompuPoint is fully optimized for mobile, tablet, and desktop devices. Download our mobile app to access courses offline, track progress, receive notifications, and learn on the go without any limitations.",
    category: "Access",
  },
  {
    id: "5",
    question: "What hardware and repair services are available?",
    answer: "We offer complete computer hardware support including device repair, on-site service booking, Annual Maintenance Contracts (AMC), hardware diagnostics, spare parts, OS installation, software setup, remote support, and managed IT services for businesses.",
    category: "Services",
  },
  {
    id: "6",
    question: "How does the Training Institute Management System work?",
    answer: "The institute management module covers complete student enrollment, batch scheduling, attendance tracking, fee collection, performance monitoring, automated certificate generation, parent communication, staff management, and comprehensive analytics reports.",
    category: "Institute",
  },
  {
    id: "7",
    question: "Is there a free trial available?",
    answer: "Yes! All plans include a 7-day free trial with no credit card required. You get full access to features included in your chosen plan during the trial period. Upgrade, downgrade, or cancel anytime.",
    category: "Pricing",
  },
  {
    id: "8",
    question: "What support options are available?",
    answer: "We provide multi-channel support including email, live chat, phone (Enterprise plan), community forums, video tutorials, and dedicated account managers for enterprise customers. Our average response time is under 2 hours.",
    category: "Support",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "Top 10 In-Demand IT Skills in 2026 Every Professional Must Know",
    excerpt: "Discover the most valuable technology skills employers are looking for and how to acquire them quickly through structured training programs.",
    content: "",
    author: "Priya Patel",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=60&h=60&fit=crop&crop=face",
    category: "Career",
    tags: ["IT Skills", "Career Growth", "Technology"],
    publishedAt: "2026-01-15",
    readTime: 7,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
    views: 8420,
    likes: 342,
  },
  {
    id: "2",
    title: "Complete Guide to Getting CompTIA A+ Certification in 30 Days",
    excerpt: "A structured 30-day study plan with resources, practice tests, and proven strategies to pass your CompTIA A+ certification on the first attempt.",
    content: "",
    author: "Rahul Sharma",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&crop=face",
    category: "Certification",
    tags: ["CompTIA", "Certification", "Study Guide"],
    publishedAt: "2026-01-12",
    readTime: 12,
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop",
    views: 6230,
    likes: 289,
  },
  {
    id: "3",
    title: "How AI is Transforming Computer Education and Training",
    excerpt: "Explore how artificial intelligence is personalizing learning experiences, automating assessments, and making quality IT education accessible to everyone.",
    content: "",
    author: "Amit Kumar",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&crop=face",
    category: "Technology",
    tags: ["AI", "Education", "Innovation"],
    publishedAt: "2026-01-08",
    readTime: 8,
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop",
    views: 9870,
    likes: 456,
  },
  {
    id: "4",
    title: "Essential Computer Maintenance Tips Every User Should Know",
    excerpt: "Regular maintenance can extend your computer's life by years. Learn the top maintenance practices, cleaning tips, and performance optimization techniques.",
    content: "",
    author: "Vikram Joshi",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop&crop=face",
    category: "Hardware",
    tags: ["Maintenance", "Hardware", "Tips"],
    publishedAt: "2026-01-05",
    readTime: 6,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop",
    views: 4560,
    likes: 178,
  },
  {
    id: "5",
    title: "Python vs JavaScript: Which Programming Language to Learn First?",
    excerpt: "A detailed comparison of Python and JavaScript for beginners — covering job market demand, learning curve, use cases, salary, and career opportunities.",
    content: "",
    author: "Neha Singh",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=60&h=60&fit=crop&crop=face",
    category: "Programming",
    tags: ["Python", "JavaScript", "Programming"],
    publishedAt: "2026-01-02",
    readTime: 10,
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&h=400&fit=crop",
    views: 11230,
    likes: 567,
  },
  {
    id: "6",
    title: "Building a Successful IT Career from Scratch: A Complete Roadmap",
    excerpt: "Step-by-step guide covering skills, certifications, portfolio building, networking strategies, and job search techniques for IT career starters.",
    content: "",
    author: "Sunita Verma",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face",
    category: "Career",
    tags: ["Career", "IT Jobs", "Roadmap"],
    publishedAt: "2025-12-28",
    readTime: 15,
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop",
    views: 7890,
    likes: 423,
  },
];

export const CERTIFICATIONS: Certification[] = [
  {
    id: "1",
    title: "Full-Stack Web Development Professional",
    issueDate: "2025-11-15",
    expiryDate: "2027-11-15",
    status: "active",
    credentialId: "CP-WD-2025-001234",
  },
  {
    id: "2",
    title: "Python Programming Specialist",
    issueDate: "2025-09-20",
    status: "active",
    credentialId: "CP-PY-2025-005678",
  },
  {
    id: "3",
    title: "Digital Marketing Professional",
    issueDate: "2025-07-10",
    expiryDate: "2026-07-10",
    status: "active",
    credentialId: "CP-DM-2025-009012",
  },
];

export const SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: "SR-001",
    type: "Hardware Repair",
    description: "Laptop screen replacement - HP Pavilion 15",
    status: "in-progress",
    createdAt: "2026-01-10",
    technician: "Sanjay Kumar",
    priority: "high",
  },
  {
    id: "SR-002",
    type: "Software Installation",
    description: "Windows 11 installation and driver setup",
    status: "completed",
    createdAt: "2026-01-08",
    technician: "Ravi Sharma",
    priority: "medium",
  },
  {
    id: "SR-003",
    type: "Remote Support",
    description: "Network configuration for office setup",
    status: "pending",
    createdAt: "2026-01-12",
    priority: "medium",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    type: "success",
    title: "Course Completed",
    message: "Congratulations! You have completed the Python Programming course.",
    read: false,
    createdAt: "2026-01-10T10:30:00Z",
  },
  {
    id: "2",
    type: "info",
    title: "New Assignment",
    message: "A new assignment has been posted in Web Development course.",
    read: false,
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "3",
    type: "success",
    title: "Certification Earned",
    message: "Your Python Programming Specialist certificate is ready for download.",
    read: true,
    createdAt: "2026-01-09T15:00:00Z",
  },
  {
    id: "4",
    type: "warning",
    title: "Service Update",
    message: "Your hardware repair request SR-001 has been assigned to a technician.",
    read: true,
    createdAt: "2026-01-09T11:00:00Z",
  },
];

export const STATS = [
  { label: "Students Enrolled", value: 125000, suffix: "+", prefix: "" },
  { label: "Courses Available", value: 280, suffix: "+", prefix: "" },
  { label: "Certifications Issued", value: 89000, suffix: "+", prefix: "" },
  { label: "Success Rate", value: 96, suffix: "%", prefix: "" },
];

export const WORKFLOW_STEPS = [
  {
    step: "01",
    title: "Register & Get Assessed",
    description: "Create your profile and take a free skill assessment to identify your strengths and learning gaps.",
    icon: "UserPlus",
  },
  {
    step: "02",
    title: "Enroll in Courses",
    description: "Choose from 280+ courses curated for your skill level, career goals, and industry requirements.",
    icon: "BookOpen",
  },
  {
    step: "03",
    title: "Learn & Practice",
    description: "Access video lessons, live sessions, hands-on labs, and AI-powered guidance at your own pace.",
    icon: "Monitor",
  },
  {
    step: "04",
    title: "Get Certified",
    description: "Pass industry-recognized assessments and receive verified digital certificates.",
    icon: "Award",
  },
  {
    step: "05",
    title: "Launch Your Career",
    description: "Use our job portal, resume builder, and placement assistance to land your dream IT role.",
    icon: "Rocket",
  },
];

export const BENEFITS = [
  {
    title: "Industry-Recognized Certifications",
    description: "Earn certifications that are trusted and recognized by top employers across India and globally.",
    icon: "BadgeCheck",
    color: "blue",
  },
  {
    title: "AI-Powered Learning",
    description: "Personalized study paths, instant doubt resolution, and smart progress tracking with AI assistance.",
    icon: "Brain",
    color: "cyan",
  },
  {
    title: "Expert Instructors",
    description: "Learn from industry veterans with 10+ years of hands-on experience in their respective domains.",
    icon: "GraduationCap",
    color: "blue",
  },
  {
    title: "Hands-On Projects",
    description: "Build a professional portfolio with real-world projects that demonstrate your skills to employers.",
    icon: "Code2",
    color: "cyan",
  },
  {
    title: "Hardware & Repair Services",
    description: "Complete computer maintenance, repair, and support services available on-site and remotely.",
    icon: "Wrench",
    color: "blue",
  },
  {
    title: "Career Placement Support",
    description: "Resume building, interview preparation, job matching, and dedicated placement assistance.",
    icon: "Briefcase",
    color: "cyan",
  },
];
